#! /bin/bash
jack_connect ossia\ score:out_0 system:playback_1
jack_connect ossia\ score:out_0 system:playback_4
jack_connect ossia\ score:out_0 system:playback_5
jack_connect ossia\ score:out_0 system:playback_6
jack_connect ossia\ score:out_0 system:playback_13
jack_connect ossia\ score:out_0 system:playback_14
jack_connect ossia\ score:out_0 system:playback_15
jack_connect ossia\ score:out_0 system:playback_16
jack_connect ossia\ score:out_0 system:playback_17
jack_connect ossia\ score:out_0 system:playback_18
jack_connect ossia\ score:out_0 system:playback_19
jack_connect ossia\ score:out_0 system:playback_20
jack_connect ossia\ score:out_0 system:playback_21
jack_connect ossia\ score:out_0 system:playback_22
jack_connect ossia\ score:out_0 system:playback_23
jack_connect ossia\ score:out_0 system:playback_32
jack_connect ossia\ score:out_0 system:playback_37
jack_connect ossia\ score:out_0 system:playback_38
jack_connect ossia\ score:out_0 system:playback_39
jack_connect ossia\ score:out_0 system:playback_40
jack_connect ossia\ score:out_0 system:playback_41

jack_connect ossia\ score:out_1 system:playback_2
jack_connect ossia\ score:out_1 system:playback_3
jack_connect ossia\ score:out_1 system:playback_7
jack_connect ossia\ score:out_1 system:playback_8
jack_connect ossia\ score:out_1 system:playback_9
jack_connect ossia\ score:out_1 system:playback_10
jack_connect ossia\ score:out_1 system:playback_11
jack_connect ossia\ score:out_1 system:playback_12
jack_connect ossia\ score:out_1 system:playback_24
jack_connect ossia\ score:out_1 system:playback_25
jack_connect ossia\ score:out_1 system:playback_26
jack_connect ossia\ score:out_1 system:playback_27
jack_connect ossia\ score:out_1 system:playback_28
jack_connect ossia\ score:out_1 system:playback_29
jack_connect ossia\ score:out_1 system:playback_30
jack_connect ossia\ score:out_1 system:playback_31
jack_connect ossia\ score:out_1 system:playback_33
jack_connect ossia\ score:out_1 system:playback_34
jack_connect ossia\ score:out_1 system:playback_35
jack_connect ossia\ score:out_1 system:playback_36
jack_connect ossia\ score:out_1 system:playback_42

